# Generated by Django 4.2.5 on 2023-11-16 19:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(choices=[('Basic  1', 'A1'), ('Basic  2', 'A2'), ('Intermediate', 'B1'), ('Upper Intermediate', 'B2'), ('Advanced', 'C1')], max_length=20)),
                ('listening', models.CharField(choices=[('Basic  1', 'A1'), ('Basic  2', 'A2'), ('Intermediate', 'B1'), ('Upper Intermediate', 'B2'), ('Advanced', 'C1')], max_length=20)),
                ('writing', models.CharField(choices=[('Basic  1', 'A1'), ('Basic  2', 'A2'), ('Intermediate', 'B1'), ('Upper Intermediate', 'B2'), ('Advanced', 'C1')], max_length=20)),
                ('speaking', models.CharField(choices=[('Basic  1', 'A1'), ('Basic  2', 'A2'), ('Intermediate', 'B1'), ('Upper Intermediate', 'B2'), ('Advanced', 'C1')], max_length=20)),
                ('equivalent', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_close_sol', models.DateField()),
                ('date_certification', models.DateField(default=datetime.date.today)),
                ('date_speaking', models.DateField()),
                ('date_writing_reading_listening', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('group', models.CharField(max_length=10)),
                ('facultad', models.CharField(blank=True, choices=[('Facultad 1', 'F1'), ('Facultad  2', 'F2'), ('Facultad 3', 'F3'), ('Facultad 4', 'F4'), ('Facultad FTE', 'FTE'), ('Facultad CITEC', 'CITEC')], max_length=100, null=True)),
                ('name', models.CharField(max_length=15)),
                ('second_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(max_length=35)),
                ('second_surname', models.CharField(max_length=35)),
                ('decano', models.CharField(max_length=150)),
                ('career', models.CharField(max_length=150)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_completo', models.CharField(max_length=150)),
                ('facultad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_has_solicitud', models.DateField(auto_now=True)),
                ('certification', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='certifications.certification')),
                ('estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='certifications.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tribunal', models.CharField(choices=[('Examenes escritos', 'Exámenes de las 4 habilidades'), ('Examen oral', 'Examen oral (speaking)'), ('Calificación de escucha', 'Calificación de escucha (listening)'), ('Calificación de escritura', 'Calificación de escritura (writing)'), ('Calificación de lectura', 'Calificación de lectura (reading)'), ('Otorgar nivel', 'Dado el nivel de las 4 habilidades, dar nivel final')], max_length=25)),
                ('jefe_tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_tribunal', to='certifications.profesor')),
                ('profesores', models.ManyToManyField(blank=True, to='certifications.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Hago_Constar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emision', models.DateField(auto_now=True)),
                ('estudiante', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='certifications.estudiante')),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.folio')),
            ],
        ),
    ]
